# -*- coding: utf-8 -*-
"""
2 haftalik kontent — har kanal uchun 28 ta post (kuniga 2 ta).
Har bir post: hook (kartochkadagi qisqa "lol qildiruvchi" matn),
caption (Telegram post matni — to'liq tushuntirish/javob), emoji.
"""

MATH_OLIMJON = [
    {"hook": "0,999... aslida 1 ga TENG. Ishonmaysizmi?", "emoji": "🤯",
     "caption": "0,999... (cheksiz takrorlanuvchi) aslida 1 ga aynan teng!\n\nIsbot: x = 0,999...\n10x = 9,999...\n10x - x = 9\n9x = 9 → x = 1\n\nDemak 0,999... = 1. Matematikada cheksizlik shunday g'alati ishlaydi 😅\nSiz avval bilardingizmi? Kommentga yozing!"},
    {"hook": "20% dan 50% ni topish 50% dan 20% ni topish bilan BIR XIL natija beradi", "emoji": "🔄",
     "caption": "50 ning 20% i qancha? Yoki 20 ning 50% i?\n\nIkkisi ham = 10!\n\nSababi: a% of b = b% of a, chunki ikkisi ham (a×b)/100 ga teng.\nBu trick foiz hisoblashni ancha tezlashtiradi. Masalan 8% of 50 ni hisoblash o'rniga 50% of 8 (ya'ni 4) ni hisoblang — tezroq!"},
    {"hook": "Monty Hall muammosi: 3 eshikdan birini tanlang, keyin fikringizni o'zgartirish g'alaba ehtimolini 2 baravar oshiradi", "emoji": "🚪",
     "caption": "3 eshik bor: birida mashina, ikkisida hech nima. Siz 1-eshikni tanlaysiz. Uy egasi 3-eshikni ochib, u yerda hech nima yo'qligini ko'rsatadi. Endi 2-eshikka o'tishingiz kerakmi?\n\nJAVOB: HA! O'tish g'alaba ehtimolini 1/3 dan 2/3 ga oshiradi.\nBu — Monty Hall muammosi, hatto olimlar orasida ham bahs-munozara chaqirgan!"},
    {"hook": "Gauss 10 yoshida 1 dan 100 gacha bo'lgan sonlarni bir necha soniyada qo'shgan", "emoji": "⚡",
     "caption": "Kichik Gauss shu trickni ishlatgan: 1+2+...+100\n\nSonlarni juftlab qo'shing: (1+100)+(2+99)+...= 101 × 50 juft = 5050\n\nFormula: n(n+1)/2\n\nShunday qilib u o'qituvchisini hайratда qoldirgan. Endi siz ham istalgan sonlar yig'indisini soniyada topa olasiz!"},
    {"hook": "Cheksiz xonali mehmonxonaga yana bitta mehmon kirishi mumkin — hatto barcha xonalar TO'LIQ bo'lsa ham", "emoji": "🏨",
     "caption": "Hilbert mehmonxonasi paradoksi: cheksiz sonli xona bor va HAMMASI band. Yana 1 mehmon keldi.\n\nYechim: har bir mehmonni bir xona narigisiga ko'chiring (1→2, 2→3, 3→4...). Endi 1-xona bo'shadi!\n\nCheksizlik bilan matematika oddiy mantiqni buzadi 🤯"},
    {"hook": "Har qanday sonning 9 ga bo'linishini 3 soniyada bilib olish usuli bor", "emoji": "🔢",
     "caption": "Trick: sonning raqamlarini qo'shing. Agar yig'indi 9 ga bo'linsa — son ham 9 ga bo'linadi!\n\nMisol: 4581 → 4+5+8+1=18 → 18 9 ga bo'linadi → demak 4581 ham bo'linadi (4581÷9=509)\n\nBuni do'stlaringizga ko'rsatib hayratga soling!"},
    {"hook": "Minus × minus nega plus bo'ladi? Ko'pchilik buni hech qachon tushuntira olmaydi", "emoji": "➖",
     "caption": "(-1) × (-1) = 1 ekanligini isbotlaymiz:\n\n(-1) × (1 + (-1)) = (-1) × 0 = 0\n(-1)×1 + (-1)×(-1) = 0\n-1 + (-1)×(-1) = 0\n(-1)×(-1) = 1 ✅\n\nMatematik qonunlar tasodifiy emas — hammasi bir-biriga bog'langan!"},
    {"hook": "Bitta A4 qog'ozni 42 marta buklasangiz, u Oygacha yetadi (nazariy jihatdan)", "emoji": "🌙",
     "caption": "Qog'oz qalinligi ~0,1mm. Har buklashda qalinlik 2 martaga oshadi: 0,1mm × 2^42 ≈ 440,000 km — bu Oygacha bo'lgan masofadan (384,000 km) ko'proq!\n\nAmalda qog'ozni 7-8 martadan ortiq buklab bo'lmaydi, lekin matematik jihatdan bu — daraja funksiyasining kuchi!"},
    {"hook": "23 kishi bir xonada bo'lsa, ikkisining tug'ilgan kuni bir xil chiqishi ehtimoli 50% dan yuqori", "emoji": "🎂",
     "caption": "Tug'ilgan kun paradoksi! Faqat 23 kishi kifoya — 365 kun bo'lsa ham.\n\nSabab: kishilar soni oshsa, JUFTLIKLAR soni tezroq o'sadi (23 kishida 253 juft bor). Har bir juft mos kelish imkoniyatiga ega.\n\n70 kishida bu ehtimol 99,9% ga chiqadi! Sinfingizda tekshirib ko'ring 👀"},
    {"hook": "Har qanday tub son (2dan tashqari) ikkiga bo'linmaydi — lekin har qanday JUFT son ikki tub songa ajraladi", "emoji": "➕",
     "caption": "Goldbach gipotezasi: har qanday 2dan katta juft son ikkita tub sonning yig'indisi sifatida yoziladi.\n\nMisol: 28 = 5+23, 100 = 3+97\n\n1742-yildan beri bu HALI HAM isbotlanmagan — kompyuterlar milliardlab sonlarni tekshirgan, hammasi to'g'ri chiqgan, lekin umumiy isbot yo'q!"},
    {"hook": "π sonining o'nlik kasrida sizning tug'ilgan kuningiz albatta bor (ehtimol bilan)", "emoji": "🥧",
     "caption": "π = 3,14159265358979... cheksiz va takrorlanmaydi (irratsional son).\n\nAgar π haqiqatan ham 'normal son' bo'lsa (bu isbotlanmagan, lekin kuchli taxmin), unda istalgan raqamlar ketma-ketligi — jumladan tug'ilgan kuningiz — undan albatta topiladi!\n\npi-yl.com saytida o'zingiznikini qidirib ko'ring 🔍"},
    {"hook": "11 ga ko'paytirishning 3 soniyalik triki bor, kalkulyator kerak emas", "emoji": "✖️",
     "caption": "2 xonali sonni 11ga ko'paytirish: raqamlarni bir-biridan ajratib, o'rtasiga yig'indisini qo'ying!\n\nMisol: 45 × 11 → 4 va 5 orasiga (4+5=9) qo'ying → 495 ✅\n\n72 × 11 → 7+2=9 → 792 ✅\n\nAgar yig'indi 10dan katta bo'lsa, birlik xonasini qoldirib, o'ndalikni oldingi raqamga qo'shing. Sinab ko'ring!"},
    {"hook": "0! (nol faktorial) nega 1 ga teng, 0 ga emas?", "emoji": "❗",
     "caption": "n! — n tagacha bo'lgan sonlarni tartiblash usullari soni.\n\n0 ta narsani NECHA XIL tartiblash mumkin? Faqat 1 xil — hech narsa qilmaslik!\n\nShuning uchun 0! = 1. Bu formula kombinatorika va ehtimollar nazariyasida ko'p joyni to'g'ri ishlashini ta'minlaydi."},
    {"hook": "Tub sonlar CHEKSIZ ko'p — buni yunon olimi 2300 yil oldin isbotlagan", "emoji": "♾️",
     "caption": "Evklid isboti: aytaylik, tub sonlar chekli — P1, P2...Pn.\n\nBarchasini ko'paytirib, 1 qo'shing: N = P1×P2×...×Pn + 1\n\nN hech qaysi Pi ga bo'linmaydi (qoldiq 1 chiqadi) — demak N ning o'zi yangi tub son yoki yangi tub songa ega. Ziddiyat! Demak tub sonlar cheksiz."},
    {"hook": "Kvadratning barcha burchaklari yig'indisi nega doim 360°?", "emoji": "🔲",
     "caption": "Har qanday to'rtburchakni 2 uchburchakka bo'lish mumkin. Uchburchak burchaklari yig'indisi = 180°.\n\n2 uchburchak = 2×180° = 360°\n\nShu formula har qanday to'rtburchak (kvadrat, romb, trapezoid) uchun ishlaydi — shakli qanday bo'lishidan qat'i nazar!"},
    {"hook": "Yoshingizni hech kimga aytmasdan, matematika orqali top uchun beraylik", "emoji": "🎯",
     "caption": "Bu klassik trick: 'Yoshingizni 5ga ko'paytiring, 3 qo'shing, 2ga ko'paytiring, natijani ayting'.\n\nBu — algebraik tenglama: agar javob = R bo'lsa, yosh = (R-6)/10\n\nBarcha 'sonni top' o'yinlari orqasida oddiy algebra tenglamasi yashiringan!"},
    {"hook": "Pascal uchburchagida har bir qator sizga sirli naqshlarni ko'rsatadi", "emoji": "🔺",
     "caption": "Pascal uchburchagi: har son tepasidagi 2 sonning yig'indisi.\n1\n1 1\n1 2 1\n1 3 3 1\n\nBu uchburchak (a+b)^n formulasidagi koeffitsientlarni, Fibonachchi sonlarini va hattoki fraktallarni o'zida yashiradi!"},
    {"hook": "Chekmas ketma-ket sonlarni qo'shsangiz ham, natija CHEKLI bo'lishi mumkin", "emoji": "🌀",
     "caption": "1/2 + 1/4 + 1/8 + 1/16 + ... = ?\n\nHar safar qolgan masofaning yarmini bosib o'tsangiz, HECH QACHON manzilga yetmaysiz — lekin masofa 1 ga yaqinlashadi!\n\nJavob: 1. Bu — geometrik qatorlar, Zenon paradoksining matematik yechimi."},
    {"hook": "Fibonachchi sonlari gulbarglar, gilos mevasi va galaktikalarda uchraydi", "emoji": "🌻",
     "caption": "1,1,2,3,5,8,13,21... har bir son oldingi ikkisining yig'indisi.\n\nKetma-ket sonlarning nisbati (13/8, 21/13...) 1,618 ga (oltin nisbat φ) yaqinlashadi.\n\nBu nisbat gullar, dengiz chig'anog'i va San Fransiskodagi galaktika spiralida ham uchraydi — tabiat matematikani yaxshi biladi!"},
    {"hook": "Sizga ma'lum har qanday 3 xonali son bilan sehrgarlik trick", "emoji": "🎩",
     "caption": "Har qanday 3 xonali sonni oling (masalan 473), o'ziga qarama-qarshi yozing (374), kattasidan kichigini ayiring, natijani teskari yozib qo'shing — natija HAR DOIM 1089 bo'ladi (agar ayirma 3 xonali bo'lsa)!\n\nSinab ko'ring va do'stlaringizni hayratga soling 🤯"},
    {"hook": "Simpson paradoksi: har guruhda A yutadi, lekin UMUMIYda B yutadi — bu mumkinmi?", "emoji": "📊",
     "caption": "Ha, mumkin! Bu — Simpson paradoksi. Statistikada guruhlarni noto'g'ri birlashtirish natijalarni butunlay teskari ko'rsatishi mumkin.\n\nMisol: shifoxona A har ikki toifada ham yuqori muvaffaqiyat ko'rsatadi, lekin umumiy statistikada B yutib chiqadi — chunki bemorlar soni notekis taqsimlangan!\n\nStatistikaga hamisha ehtiyot bo'lib qarang 👁️"},
    {"hook": "Har qanday uchburchak ichidagi bir nuqtadan barcha uchlargacha bo'lgan masofa yig'indisi minimal bo'ladigan joy bor", "emoji": "📐",
     "caption": "Bu nuqta — Fermat nuqtasi. Uni topish uchun har tomonga tashqi tomon uchburchak yasab, ularning markazlarini bog'lash kerak.\n\nBu shunchaki geometrik qiziqarli fakt emas — logistika va tarmoq dizaynida ENG QISQA yo'llarni topishda ishlatiladi!"},
    {"hook": "Ikkita bir xil o'lchamli pizza kesib, ulardan uchinchi pizza yasash mumkin (matematik jihatdan)", "emoji": "🍕",
     "caption": "Bu — Banach-Tarski paradoksi (soddalashtirilgan holati)! Nazariy jihatdan, sferik jismni cheklangan bo'laklarga bo'lib, ularni qayta yig'ib, HAJMI 2 BARAVAR kattaroq shar hosil qilish mumkin.\n\nBuning siri — cheksiz nuqtalar to'plami bilan ishlashda. Amalda pizza bilan bajarib bo'lmaydi, lekin matematikada bu — isbotlangan haqiqat!"},
    {"hook": "13 juma kuni nega ba'zilar uchun 'baxtsiz' — bu haftaning kunlari qanday taqsimlanishi bilan bog'liq", "emoji": "🗓️",
     "caption": "Qiziq fakt: har yilda kamida bitta, ko'pi bilan uchta 13-juma bo'lishi SHART — bu kalendar matematikasi (Gregorian kalendar 400 yillik davr ichida takrorlanadi) tufayli isbotlangan qonuniyat!"},
    {"hook": "Shaxmat taxtasidagi barcha katakchalarga guruch donalarini ikkilantirib qo'ysangiz, natija Yer aholisini och qoldiradi", "emoji": "♟️",
     "caption": "1-katakka 1 dona, 2-ga 2, 3-ga 4... 64-katakka qadar ikkilantirib borsangiz:\n\n2^64 - 1 = 18,446,744,073,709,551,615 dona guruch!\n\nBu — butun dunyo guruch hosilidan minglab yillar uchun yetadigan miqdor. Daraja funksiyasi shunchalik tez o'sadi!"},
    {"hook": "Nega har qanday uchburchakning eng katta burchagi qarshisida eng uzun tomon joylashadi?", "emoji": "🔻",
     "caption": "Bu — sinuslar teoremasining natijasi: a/sin(A) = b/sin(B) = c/sin(C)\n\nBurchak katta bo'lsa, uning sinusi ham katta, demak qarama-qarshi tomon ham uzunroq bo'lishi SHART. Geometriya har doim mantiqiy!"},
    {"hook": "Bitta doiraviy pizzani TENG 7 bo'lakka faqat 3 to'g'ri chiziq bilan bo'lish mumkin", "emoji": "🔪",
     "caption": "'Pancake bo'lish muammosi': n ta to'g'ri chiziq doirani ko'pi bilan (n²+n+2)/2 bo'lakka bo'ladi.\n\n3 chiziq uchun: (9+3+2)/2 = 7 bo'lak!\n\nLekin bo'laklarning TENG bo'lishi uchun chiziqlarni to'g'ri joylashtirish kerak — bu geometrik optimallashtirish masalasi."},
    {"hook": "Kubning har tomonini 2 martaga oshirsangiz, hajmi necha marta o'sadi? Javob ko'pchilikni hayratga soladi", "emoji": "🧊",
     "caption": "Ko'pchilik '2 marta' deb o'ylaydi, lekin JAVOB: 8 MARTA!\n\nHajm = tomon³, shuning uchun (2a)³ = 8a³\n\nShu sababli katta quti kichigidan ko'p marta ko'proq narsa sig'diradi — bu kub qonuni, dizaynda va fizikada juda muhim!"},
]

FAKTURA = [
    {"hook": "Sakkizoyoqning 3 ta yuragi va ko'k qoni bor", "emoji": "🐙",
     "caption": "Sakkizoyoq (octopus) 3 yurakka ega: ikkisi jabralarga qon haydaydi, bittasi qolgan tanaga.\n\nQoni esa temir o'rniga MIS asosli oqsil (gemosianin) tufayli ko'k rangda! Bu ularga sovuq va kam kislorodli suvlarda yashashga yordam beradi."},
    {"hook": "Venerada bir kun (o'z o'qi atrofida) Yerdagi bir yildan UZUNROQ", "emoji": "🪐",
     "caption": "Venera o'z o'qi atrofida juda sekin aylanadi — bir marta aylanish 243 Yer kuni davom etadi.\n\nLekin Quyosh atrofida aylanishi (bir yili) faqat 225 Yer kuni!\n\nDemak Venerada 'kun' 'yil'dan uzunroq — Quyosh sistemasidagi eng g'alati holatlardan biri."},
    {"hook": "Arxeologlar 3000 yillik qadimgi Misr qabridan hali ham yeyish mumkin bo'lgan asal topgan", "emoji": "🍯",
     "caption": "Asal deyarli abadiy chidamli mahsulot — chunki unda suv juda kam va tabiiy antibakterial xususiyati bor.\n\nTo'g'ri saqlansa (yopiq idishda), asal minglab yillar davomida buzilmaydi. Qadimgi Misr piramidalaridan topilgan asal namunalari hali ham iste'mol qilish uchun yaroqli deb hisoblanadi!"},
    {"hook": "Siz tug'ilganda 300 ta suyakka ega bo'lgansiz, hozir esa faqat 206 ta", "emoji": "🦴",
     "caption": "Chaqaloqlarda ko'proq mayda suyaklar bor — ular o'sish jarayonida bir-biriga QO'SHILIB ketadi.\n\nMasalan bosh suyagi bo'laklari, umurtqa pog'onasining pastki qismi — hammasi vaqt o'tishi bilan birlashadi. Shuning uchun kattalar tanasida atigi 206 ta suyak qoladi."},
    {"hook": "Banan botanik jihatdan meva emas — bu YASHIL O'T!", "emoji": "🍌",
     "caption": "Banan daraxti aslida daraxt emas — u yog'och tanaga ega bo'lmagan eng katta o'tsimon o'simlik!\n\nQizig'i, banan botanik ma'noda 'berry' (danakli meva) turkumiga kiradi — go'shtli, urug'siz mevasi bilan.\n\nTabiat ba'zan biz o'ylagandan ancha g'alati!"},
    {"hook": "Ba'zi toshbaqalar 150 yildan ortiq yashaydi — insondan ko'proq", "emoji": "🐢",
     "caption": "Galapagos toshbaqalari 150-190 yilgacha yashashi qayd etilgan!\n\nUlarning sekin metabolizmi, past tana harorati va DNK ta'mirlash mexanizmlari qarishni sekinlashtiradi. Olimlar hozir shu mexanizmlarni inson uzoq umr ko'rishi uchun o'rganishmoqda."},
    {"hook": "Yerning ichki yadrosi Quyosh yuzasidan HAM issiqroq", "emoji": "🌋",
     "caption": "Yer yadrosi harorati taxminan 5,400°C — bu Quyoshning tashqi yuzasi (~5,500°C)ga juda yaqin, ba'zi hisoblarda undan ham issiqroq!\n\nBu issiqlik — Yer paydo bo'lishidan qolgan qoldiq issiqlik va radioaktiv parchalanish natijasi."},
    {"hook": "Karam qisqichbaqa (mantis shrimp) ko'zi 16 xil rang retseptoriga ega, insonda faqat 3 ta", "emoji": "🦐",
     "caption": "Inson ko'zi RGB (qizil, yashil, ko'k) — 3 retseptor bilan barcha ranglarni ko'radi.\n\nMantis shrimp esa 16 xil retseptorga ega, jumladan UV va polarizatsiyalangan yorug'likni ham ko'radi!\n\nQizig'i, olimlar buni odam miyasi qanchalik samarali rang qayta ishlashini tushunish uchun o'rganadi."},
    {"hook": "Voyager 1 kosmik kemasi 1977-yilda uchirilgan va HALI HAM Yerga signal yuboradi", "emoji": "🛰️",
     "caption": "Voyager 1 — insoniyat yasagan Yerdan ENG UZOQDAGI ob'ekt, hozir yulduzlararo fazoda (23+ milliard km uzoqlikda)!\n\nSignal Yerga yetib kelishi uchun 20+ soat kerak. Batareyasi 2025-yillar atrofida to'liq tugashi kutilmoqda — 48 yildan ortiq ishlagan kosmik apparat!"},
    {"hook": "Ba'zi meduzalar biologik jihatdan hech qachon o'lmaydi", "emoji": "🎐",
     "caption": "Turritopsis dohrnii turi meduzasi — 'abadiy meduza' deb ataladi.\n\nStress yoki jarohat vaqtida u o'z hujayralarini yosh holatiga QAYTARA OLADI — go'yo qaridan chaqaloqqa aylanish kabi! Nazariy jihatdan bu jarayonni cheksiz takrorlash mumkin."},
    {"hook": "Muz tog'ining (aysberg) faqat 10% qismi suv yuzasida ko'rinadi", "emoji": "🧊",
     "caption": "Muz suvdan biroz yengilroq (zichligi kam), shuning uchun suzadi — lekin faqat 1/10 qismi ko'rinadi.\n\nShu sababli Titanik fojiasi sodir bo'lgan — sirtdagi kichik ko'ringan qism ostida ulkan muz massasi yashiringan edi!"},
    {"hook": "Yer tarixidagi eng qisqa urush bor-yo'gi 38 daqiqa davom etgan", "emoji": "⚔️",
     "caption": "1896-yilgi Angliya-Zanzibar urushi rasmiy ravishda tarixdagi eng qisqa urush hisoblanadi — atigi 38 daqiqa!\n\nZanzibar Angliya ultimatumiga rozi bo'lmagach boshlangan, ammo tezda Angliya g'alabasi bilan tugagan."},
    {"hook": "Xitoyning Buyuk devori koinotdan yalang' ko'z bilan ko'RINMAYDI — bu keng tarqalgan mif", "emoji": "🚫",
     "caption": "Ko'pchilik bu mifga ishonadi, lekin astronavtlar tasdiqlashicha, devor juda tor (o'rtacha 6-9m kenglikda) bo'lgani uchun yalang' ko'z bilan orbitadan ajratib bo'lmaydi.\n\nHatto Xitoy o'zining birinchi astronavti Yang Liveini shu haqida so'rashganda, u ko'rmaganini aytgan!"},
    {"hook": "Yashil chaqmoq (green flash) — quyosh botayotganda ba'zan ko'rinadigan haqiqiy optik hodisa", "emoji": "🌅",
     "caption": "Bu — afsona emas! Ayrim sharoitlarda (tekis ufq, tiniq havo, odatda dengiz ustida) quyosh to'liq botishidan oldin bir necha soniya YASHIL rangda yaltirab ko'rinadi.\n\nBu — atmosfera yorug'likni prizma kabi sindiradi, va yashil rang oxirgi bo'lib g'oyib bo'ladi."},
    {"hook": "Ba'zi qutb yulduzlari (Polaris) nurini biz hozir ko'rayotganimiz, aslida 400 yil oldin chiqqan", "emoji": "⭐",
     "caption": "Yulduzlar juda uzoqda joylashgani uchun ularning yorug'ligi bizga yetib kelishi vaqt talab qiladi.\n\nPolaris ~400 yorug'lik yili uzoqlikda — demak biz hozir ko'ryotgan nur XVII asrda chiqqan! Osmonga qarash — aslida o'tmishga qarash demakdir."},
    {"hook": "Chaqmoq havoni Quyosh yuzasidan issiqroq qiladi", "emoji": "⚡",
     "caption": "Chaqmoq chaqilgan joyda harorat 30,000°C ga yetadi — Quyosh yuzasi (5,500°C)dan 5 baravar issiqroq!\n\nBu keskin issiqlik havoni portlatib, momaqaldiroq tovushini (gumburlash) hosil qiladi."},
    {"hook": "Insonning burni 1 trillion xil hidni farqlashga qodir", "emoji": "👃",
     "caption": "Ilgari insonlar faqat 10,000 hidni farqlaydi deb o'ylashardi, lekin 2014-yilgi tadqiqot buni QAYTA KO'RIB CHIQDI — natija: 1 TRILLIONdan ortiq!\n\nInson hid bilish tizimi ilgari o'ylangandan ancha murakkab va sezgir ekan."},
    {"hook": "Kimberlit vulqonlari olmoslarni Yer yuzasiga necha SOAT ichida chiqarib tashlaydi", "emoji": "💎",
     "caption": "Olmoslar Yer qa'rida 150+ km chuqurlikda, ulkan bosim va issiqlik ostida million yillar davomida hosil bo'ladi.\n\nLekin kimberlit vulqon otilishi ularni yuzaga bir necha SOAT ichida olib chiqadi — geologik jarayonlar odatda sekin, ammo bu holat ajablanarli tezlikda sodir bo'ladi!"},
    {"hook": "Antarktida — Yerdagi eng katta chuchuk suv zahirasi, garchi u muz bo'lsa ham", "emoji": "🧊",
     "caption": "Antarktida muzligi dunyodagi chuchuk suvning ~70% ini o'zida saqlaydi!\n\nAgar bu muz to'liq erisa, okean sathi 60 metrdan ortiq ko'tarilishi mumkin — bu butun qit'alarning qirg'oq chizig'ini butunlay o'zgartirardi."},
    {"hook": "Yupiterdagi bo'ron (Katta Qizil Dog') Yerdan KATTAROQ", "emoji": "🪐",
     "caption": "Great Red Spot — Yupiterdagi ulkan bo'ron, kamida 350 yildan beri davom etayotgani ma'lum!\n\nUning kengligi ~16,000 km — bu butun Yer sayyorasidan kattaroq. Shamol tezligi 400+ km/soatga yetadi."},
    {"hook": "Insonning DNKsi bananga 60% o'xshash", "emoji": "🧬",
     "caption": "Barcha tirik organizmlar hujayra darajasida umumiy jarayonlarni bajaradi (energiya ishlab chiqarish, o'sish, ko'payish) — shuning uchun DNKda umumiylik kutilgan.\n\nInson va shimpanze DNKsi esa 98%+ o'xshash — bu bizning eng yaqin qarindoshimiz ekanini ko'rsatadi!"},
    {"hook": "Qora tuynuk atrofida vaqt SEKINROQ oqadi — bu ilmiy-fantastika emas", "emoji": "🕳️",
     "caption": "Einshteynning umumiy nisbiylik nazariyasiga ko'ra, kuchli tortishish maydonida (qora tuynuk yaqinida) vaqt sekinlashadi.\n\n'Interstellar' filmidagi vaqt farqi sahnasi — bu haqiqiy fizika qonuniga asoslangan, va GPS sun'iy yo'ldoshlari ham shu effektni hisobga olib ishlaydi!"},
    {"hook": "Dengiz suvidagi tuz millionlab yillar davomida daryolar orqali yig'ilgan", "emoji": "🌊",
     "caption": "Yomg'ir suvi tog' jinslaridan minerallarni yuvib, daryolar orqali okeanga olib boradi.\n\nOkeandan suv faqat bug'lanish yo'li bilan chiqadi (tuzni QOLDIRIB) — shuning uchun tuz milliardlab yillar davomida to'planib, dengiz suvini sho'r qilgan!"},
    {"hook": "Lotus guli barglari o'z-o'zini tozalash qobiliyatiga ega", "emoji": "🪷",
     "caption": "Lotus bargi yuzasi mikroskopik darajada g'adir-budir tuzilishga ega — bu suv tomchilarini sirpanchiq qilib, chang-to'zonni o'zi bilan olib ketadi.\n\nBu hodisa 'Lotus effekti' deb ataladi va hozir chang tortmaydigan sirtlar, bo'yoqlar yaratishda ishlatiladi!"},
    {"hook": "Bitta chaqmoq zaryadi 100 million voltgacha yetadi", "emoji": "🌩️",
     "caption": "Odatiy uy elektr tarmog'i 220 voltda ishlaydi — chaqmoq esa BUNDAN 450,000 MARTA kuchliroq!\n\nShuning uchun chaqmoq daraxtlarni chaqib, qumni shishaga aylantirib (fulgurit hosil qilib) yuboradi."},
    {"hook": "Muzlab qolgan mamont go'shti 40,000 yildan keyin ham topilgan", "emoji": "🦣",
     "caption": "Sibirning abadiy muzlagan tuprog'ida (permafrost) saqlangan mamont qoldiqlari shu qadar yaxshi saqlangan-ki, olimlar ularning DNKsini o'rganib, hatto 'mamontni qayta tiriltirish' loyihalarini rejalashtirishmoqda!"},
    {"hook": "Baliqlarning ba'zi turlari elektr zaryadi bilan ovqat izlaydi", "emoji": "🐡",
     "caption": "Electric eel (elektr ilonbaliq) 600 voltgacha zaryad hosil qila oladi — bu odamni behush qilishga yetarli!\n\nUlar bu qobiliyatni ov qilish, himoyalanish va hatto atrofni 'his qilish' (elektrolokatsiya) uchun ishlatadi."},
    {"hook": "Bir tomchi suvda millionlab mikroorganizm yashaydi", "emoji": "🔬",
     "caption": "Toza ko'rinadigan bir tomchi hovuz suvida mikroskop ostida minglab, ba'zan millionlab bakteriya va mikroorganizmlar ko'rinadi!\n\nBu mikroorganizmlar ekotizimning asosi — ular organik chiqindilarni parchalab, boshqa hayot turlari uchun ozuqa zanjirini boshlaydi."},
]

MATEMATIKA_MILLIY = [
    {"hook": "x² - 5x + 6 = 0 tenglamasini 10 soniyada yechish usuli", "emoji": "🧮",
     "caption": "MASALA: x² - 5x + 6 = 0\n\nYECHIM: ko'paytmasi 6, yig'indisi 5 bo'lgan sonlarni topamiz → 2 va 3\n(x-2)(x-3) = 0\nx₁=2, x₂=3\n\nBu — ko'paytuvchilarga ajratish usuli, diskriminant hisoblashdan tezroq!"},
    {"hook": "To'g'ri burchakli uchburchakda gipotenuza 13, bir tomoni 5 — ikkinchisini top", "emoji": "📐",
     "caption": "MASALA: to'g'ri burchakli uchburchak, gipotenuza c=13, tomon a=5. b ni top.\n\nYECHIM (Pifagor teoremasi): a²+b²=c²\n25+b²=169\nb²=144\nb=12\n\nJavob: 12. Bu — mashhur '5-12-13' Pifagor uchligi!"},
    {"hook": "log₂8 + log₂4 ni bir necha soniyada hisoblash", "emoji": "📊",
     "caption": "MASALA: log₂8 + log₂4 = ?\n\nYECHIM: log qoidasi — logₐb+logₐc = logₐ(b×c)\nlog₂8 + log₂4 = log₂(8×4) = log₂32 = log₂2⁵ = 5\n\nJavob: 5. Logarifm qoidalarini bilish hisoblashni tezlashtiradi!"},
    {"hook": "Arifmetik progressiyada a₁=3, d=4. 20-hadni top", "emoji": "🔢",
     "caption": "MASALA: a₁=3, d=4. a₂₀ ni top.\n\nYECHIM: aₙ = a₁+(n-1)d\na₂₀ = 3+(20-1)×4 = 3+76 = 79\n\nJavob: 79. Bu formula DTM'da eng ko'p uchraydigan formulalardan biri!"},
    {"hook": "Radiusi 7 bo'lgan doira yuzini π orqali hisoblash", "emoji": "⭕",
     "caption": "MASALA: R=7. Doira yuzini top (π≈22/7 dan foydalaning).\n\nYECHIM: S=πR²\nS = (22/7) × 7² = (22/7) × 49 = 22×7 = 154\n\nJavob: 154 kv. birlik. R qiymati 7ning ko'paytmasi bo'lganda 22/7 ishlatish hisoblashni osonlashtiradi!"},
    {"hook": "2 nomalum bilan tizim: x+y=10, x-y=4. Tezkor yechim", "emoji": "⚖️",
     "caption": "MASALA: x+y=10, x-y=4\n\nYECHIM: ikkita tenglamani qo'shamiz:\n2x=14 → x=7\nBirinchisiga qo'yamiz: 7+y=10 → y=3\n\nJavob: x=7, y=3. Qo'shish usuli — chiqarish kerak bo'lganda eng tez yo'l!"},
    {"hook": "sin30° + cos60° ni yodda hisoblash", "emoji": "📐",
     "caption": "MASALA: sin30° + cos60° = ?\n\nYECHIM: sin30° = 1/2, cos60° = 1/2\n1/2 + 1/2 = 1\n\nJavob: 1. Burchaklar jadvalini yodlab olish DTM vaqtini ancha tejaydi!"},
    {"hook": "Geometrik progressiyada b₁=2, q=3. Birinchi 4 hadning yig'indisini top", "emoji": "📈",
     "caption": "MASALA: b₁=2, q=3, S₄ ni top.\n\nYECHIM: Sₙ = b₁(qⁿ-1)/(q-1)\nS₄ = 2(3⁴-1)/(3-1) = 2(81-1)/2 = 2×80/2 = 80\n\nJavob: 80. Geometrik progressiya formulasi eksponensial o'sishni tasvirlaydi!"},
    {"hook": "50 ning 30% qancha bo'ladi — bosh hisoblab topish usuli", "emoji": "💯",
     "caption": "MASALA: 50 ning 30%ini top.\n\nYECHIM: 10% of 50 = 5 (nol chiqarib tashlash)\n30% = 3 × 10% = 3×5 = 15\n\nJavob: 15. Foizni 10% orqali hisoblash — DTMda vaqtni tejashning eng oson usuli!"},
    {"hook": "y=2x+3 va y=-x+9 chiziqlari qayerda kesishadi?", "emoji": "📉",
     "caption": "MASALA: y=2x+3, y=-x+9. Kesishish nuqtasini top.\n\nYECHIM: 2x+3 = -x+9\n3x = 6\nx = 2\ny = 2(2)+3 = 7\n\nJavob: (2,7). Ikki chiziqning kesishishi — ularning tenglamalarini tenglashtirish demakdir!"},
    {"hook": "Kub hajmi 27 bo'lsa, uning qirrasi qancha?", "emoji": "🧊",
     "caption": "MASALA: V=27. Qirra uzunligini top.\n\nYECHIM: V=a³\n27=a³\na=∛27=3\n\nJavob: 3. Kub ildizini bilish — ko'p geometrik masalalarni tez yechish kaliti!"},
    {"hook": "3 zar bir vaqtda tashlansa, hammasida 6 chiqish ehtimoli qancha?", "emoji": "🎲",
     "caption": "MASALA: 3 ta zar tashlanadi. Barchasida 6 chiqish ehtimolini top.\n\nYECHIM: har bir zarda 6 chiqish ehtimoli = 1/6\nMustaqil voqealar: 1/6 × 1/6 × 1/6 = 1/216\n\nJavob: 1/216. Mustaqil voqealar ehtimoli — ko'paytirish orqali topiladi!"},
    {"hook": "f(x)=x²-4 funksiyaning aniqlanish sohasi va nollarini top", "emoji": "📊",
     "caption": "MASALA: f(x)=x²-4. Aniqlanish sohasi va nollarini top.\n\nYECHIM: kvadrat funksiya — barcha x uchun aniqlangan → D(f)=(-∞;+∞)\nNollari: x²-4=0 → x²=4 → x=±2\n\nJavob: D(f)=R, nollari x=2 va x=-2"},
    {"hook": "Uchburchak yuzini 3 tomoni orqali (Geron formulasi) topish", "emoji": "📐",
     "caption": "MASALA: tomonlari a=3, b=4, c=5 bo'lgan uchburchak yuzini top.\n\nYECHIM: bu — to'g'ri burchakli uchburchak (3-4-5 Pifagor uchligi)!\nS = (1/2)×a×b = (1/2)×3×4 = 6\n\nJavob: 6 kv. birlik. Pifagor uchliklarini tanish — vaqtni ancha tejaydi!"},
    {"hook": "2ˣ = 32 tenglamasini yechish", "emoji": "⚡",
     "caption": "MASALA: 2ˣ = 32\n\nYECHIM: 32 ni 2 ning darajasi sifatida yozamiz: 32=2⁵\n2ˣ=2⁵\nx=5\n\nJavob: x=5. Ko'rsatkichli tenglamalarda ikkala tomonni bir xil asosga keltirish — asosiy usul!"},
    {"hook": "To'g'ri to'rtburchakning perimetri 20, eni 4. Yuzini top", "emoji": "▭",
     "caption": "MASALA: P=20, eni=4. Yuzini top.\n\nYECHIM: P=2(a+b) → 20=2(a+4) → a+4=10 → a=6\nS=a×b=6×4=24\n\nJavob: 24 kv. birlik"},
    {"hook": "|x-3|=5 tenglamasini yechish — 2 javob chiqadi!", "emoji": "🔀",
     "caption": "MASALA: |x-3|=5\n\nYECHIM: modul ikki holat beradi:\nx-3=5 → x=8\nx-3=-5 → x=-2\n\nJavob: x=8 yoki x=-2. Modul tenglamalarda HAR DOIM 2 holatni tekshirish kerak!"},
    {"hook": "Uchburchak burchaklari nisbati 2:3:4. Har bir burchakni top", "emoji": "📐",
     "caption": "MASALA: burchaklar nisbati 2:3:4. Har birini top.\n\nYECHIM: 2k+3k+4k=180° → 9k=180° → k=20°\nBurchaklar: 40°, 60°, 80°\n\nJavob: 40°, 60°, 80°. Nisbat masalalarida yig'indini bilish — kalit!"},
    {"hook": "√48 ni eng sodda ko'rinishga keltirish", "emoji": "√",
     "caption": "MASALA: √48 ni soddalashtiring.\n\nYECHIM: 48=16×3\n√48=√16×√3=4√3\n\nJavob: 4√3. Katta son ostidagi ildizni to'liq kvadratga ajratib chiqarish — DTMda tez-tez uchraydi!"},
    {"hook": "Silindr radiusi 3, balandligi 5. Hajmini top", "emoji": "🥫",
     "caption": "MASALA: r=3, h=5. Silindr hajmini top (π≈3,14).\n\nYECHIM: V=πr²h\nV=3,14×9×5=141,3\n\nJavob: ≈141,3 kub birlik"},
    {"hook": "3 kishi ishni 6 kunda tugatadi. 2 kishi shu ishni necha kunda tugatadi?", "emoji": "👷",
     "caption": "MASALA: 3 kishi 6 kunda. 2 kishi necha kunda?\n\nYECHIM: ish hajmi = 3×6=18 kishi-kun\n2 kishi uchun: 18/2=9 kun\n\nJavob: 9 kun. Ish masalalarida 'kishi-kun' — universal o'lchov birligi!"},
    {"hook": "Ehtimollar: qutida 5 qizil, 3 ko'k shar. Tasodifan qizil shar olish ehtimoli", "emoji": "🎯",
     "caption": "MASALA: 5 qizil, 3 ko'k shar (jami 8). Qizil olish ehtimoli?\n\nYECHIM: P=qulay holatlar/barcha holatlar = 5/8\n\nJavob: 5/8 = 0,625 = 62,5%"},
    {"hook": "cos²x + sin²x qiymati har doim nechaga teng?", "emoji": "🔵",
     "caption": "MASALA: cos²x+sin²x=?\n\nYECHIM: bu — trigonometriyaning ASOSIY ayniyati (Pifagor ayniyati)\ncos²x+sin²x=1 — x ning HAR QANDAY qiymati uchun to'g'ri!\n\nJavob: 1"},
    {"hook": "5 xonali eng katta va eng kichik sonlar ayirmasini top", "emoji": "🔢",
     "caption": "MASALA: 5 xonali eng katta va eng kichik sonlar ayirmasi.\n\nYECHIM: eng katta = 99999, eng kichik = 10000\n99999-10000=89999\n\nJavob: 89999"},
    {"hook": "Kvadrat tenglama diskriminanti manfiy bo'lsa nima bo'ladi?", "emoji": "❓",
     "caption": "MASALA: x²+x+1=0 ning haqiqiy ildizlari bormi?\n\nYECHIM: D=b²-4ac=1-4=-3\nD<0 → haqiqiy ildizlar YO'Q!\n\nJavob: haqiqiy sonlar to'plamida yechim yo'q. D belgisini tekshirish — vaqtni behuda hisoblashdan qutqaradi!"},
    {"hook": "Trapetsiyaning asoslari 6 va 10, balandligi 4. Yuzini top", "emoji": "🔷",
     "caption": "MASALA: a=6, b=10, h=4. Trapetsiya yuzini top.\n\nYECHIM: S=(a+b)/2 × h = (6+10)/2 × 4 = 8×4=32\n\nJavob: 32 kv. birlik"},
    {"hook": "Ikkita sonning YIG'INDISI 15, KO'PAYTMASI 56. Sonlarni top", "emoji": "🔍",
     "caption": "MASALA: x+y=15, xy=56\n\nYECHIM: bu — kvadrat tenglamaga keltiriladi: t²-15t+56=0\nD=225-224=1, t=(15±1)/2\nt₁=8, t₂=7\n\nJavob: sonlar 7 va 8"},
    {"hook": "Uchburchak medianalari kesishgan nuqta tomonlarni qanday nisbatda bo'ladi?", "emoji": "📐",
     "caption": "MASALA: uchburchak medianalari kesishish nuqtasi (og'irlik markazi) medianani qanday nisbatda bo'ladi?\n\nYECHIM: bu — geometriyaning muhim xossasi: og'irlik markazi har bir medianani UCHDAN UCHIGA nisbatan 2:1 nisbatda bo'ladi (uchdan uzoqroq qismi katta).\n\nJavob: 2:1"},
]

FIZIKA_MILLIY = [
    {"hook": "10 metr balandlikdan tashlangan jism qanday tezlikda yerga uradi?", "emoji": "🍎",
     "caption": "MASALA: h=10m, erkin tushish (g=10 m/s²). Yerga urilish tezligini top.\n\nYECHIM: v²=2gh\nv²=2×10×10=200\nv=√200≈14,1 m/s\n\nJavob: ≈14,1 m/s (~50 km/soat!)"},
    {"hook": "Massa 2kg jism 5 m/s tezlikda harakatlanmoqda. Kinetik energiyasini top", "emoji": "🏃",
     "caption": "MASALA: m=2kg, v=5m/s. Kinetik energiyani top.\n\nYECHIM: Ek=mv²/2\nEk=2×25/2=25\n\nJavob: 25 Joul"},
    {"hook": "Nega kosmosda ovoz eshitilmaydi, garchi portlash bo'lsa ham?", "emoji": "🚀",
     "caption": "Ovoz — TOVUSH TO'LQINI, u tarqalishi uchun MODDIY MUHIT (havo, suv) kerak.\n\nKosmosda vakuum bor — molekulalar yo'q, shuning uchun tovush to'lqinlari tarqala olmaydi.\n\nShuning uchun barcha kino/serial kosmik jangalarida eshitiladigan portlash tovushlari — badiiy tasavvur, ilmiy jihatdan noto'g'ri!"},
    {"hook": "Kuch 20N, masofa 5m bo'lsa, bajarilgan ishni top", "emoji": "💪",
     "caption": "MASALA: F=20N, s=5m (kuch yo'nalishi harakat bo'ylab). Ishni top.\n\nYECHIM: A=F×s\nA=20×5=100\n\nJavob: 100 Joul"},
    {"hook": "Nega Yer sun'iy yo'ldoshlari doim tushib ketmaydi?", "emoji": "🛰️",
     "caption": "Sun'iy yo'ldosh doimo Yer tomon 'tushib' turadi — lekin shu vaqtda yon tomonga ham juda tez harakatlanadi.\n\nBu ikki harakat birlashib, ORBITA hosil qiladi — Nyutonning birinchi qonuni asosida, agar tortishish yo'q bo'lsa, yo'ldosh to'g'ri chiziq bo'ylab uchib ketardi!"},
    {"hook": "Suvning qaynash harorati tog' cho'qqisida past bo'ladi — sababi nima?", "emoji": "🏔️",
     "caption": "Qaynash — suyuqlik bosimi ATMOSFERA BOSIMIGA teng bo'lganda boshlanadi.\n\nTog' cho'qqisida atmosfera bosimi PAST, shuning uchun suv 100°C ga yetmasdanoq qaynay boshlaydi (masalan Everestda ~68°C da!).\n\nShu sababli tog'da tuxum pishirish qiyinroq — harorat past bo'lgani uchun."},
    {"hook": "Kuzgu (ko'zgu) tekis bo'lsa, tasvir qanday hosil bo'ladi — fizik qonun bilan tushuntiring", "emoji": "🪞",
     "caption": "Tekis ko'zguda aks etish qonuni ishlaydi: tushish burchagi = qaytish burchagi.\n\nNatijada hosil bo'lgan tasvir — VIRTUAL, TO'G'RI (aylanmagan) va predmet bilan BIR XIL o'lchamda, lekin ko'zgu OLDIDA emas, ORTIDA joylashgandek ko'rinadi."},
    {"hook": "2 rezistor (10Ω va 20Ω) ketma-ket ulansa, umumiy qarshilikni top", "emoji": "🔌",
     "caption": "MASALA: R₁=10Ω, R₂=20Ω, ketma-ket ulanish.\n\nYECHIM: ketma-ket ulanishda qarshiliklar QO'SHILADI\nR=R₁+R₂=10+20=30Ω\n\nJavob: 30Ω"},
    {"hook": "Xuddi shu rezistorlar PARALEL ulansa, qarshilik kamayadi — nega?", "emoji": "🔀",
     "caption": "MASALA: R₁=10Ω, R₂=20Ω, parallel ulanish.\n\nYECHIM: 1/R=1/R₁+1/R₂=1/10+1/20=3/20\nR=20/3≈6,67Ω\n\nJavob: ≈6,67Ω. Parallel ulanishda tok uchun KO'PROQ yo'l ochiladi, shuning uchun umumiy qarshilik KAMAYADI!"},
    {"hook": "Nega mikroto'lqinli pech (mikrovolnovka) ichida metall qo'yish xavfli?", "emoji": "⚠️",
     "caption": "Mikroto'lqin pechi elektromagnit to'lqinlar orqali ishlaydi. Metall bu to'lqinlarni YUTMAYDI, balki AKS ETTIRADI va o'zida kuchli elektr toklarini hosil qiladi.\n\nBu — uchqun (chaqmoq kabi kichik razryad) va potensial yong'inga olib kelishi mumkin. Shuning uchun metall idish/vilka pechga qo'yilmaydi!"},
    {"hook": "Avtomobil 20 m/s tezlikda 4 soniyada to'xtadi. Tormozlash tezlanishini top", "emoji": "🚗",
     "caption": "MASALA: v₀=20m/s, v=0, t=4s. Tezlanishni top.\n\nYECHIM: a=(v-v₀)/t\na=(0-20)/4=-5\n\nJavob: -5 m/s² (manfiy — tormozlanish, tezlik kamayishini bildiradi)"},
    {"hook": "Nega osmon KO'K rangda ko'rinadi, Quyosh esa oq/sariq?", "emoji": "🌤️",
     "caption": "Quyosh nuri barcha ranglardan iborat. Atmosferadagi molekulalar QISQA to'lqin uzunlikdagi (ko'k/moviy) nurni KUCHLIROQ sochib yuboradi (Rayleigh sochilishi).\n\nShuning uchun osmonning har tomonidan ko'k rang kelib, biz osmonni ko'k ko'ramiz — quyoshning o'zidan esa qolgan ranglar (sariq-oq) yetib keladi!"},
    {"hook": "Massa 5kg jism 2 m/s² tezlanish bilan harakatlansa, unga ta'sir etuvchi kuchni top", "emoji": "⚙️",
     "caption": "MASALA: m=5kg, a=2m/s². Kuchni top.\n\nYECHIM: Nyutonning 2-qonuni: F=ma\nF=5×2=10\n\nJavob: 10 Newton"},
    {"hook": "Nega kosmonavtlar xalqaro kosmik stansiyada 'vaznsiz' bo'ladi, garchi tortishish kuchi bo'lsa ham?", "emoji": "👨‍🚀",
     "caption": "Ko'pchilik o'ylaydi — kosmosda tortishish yo'q. Bu XATO!\n\nISS orbitasida tortishish kuchi Yerdagidan atigi ~10% kamroq. Kosmonavtlar 'vaznsiz' ko'rinishining sababi — ular stansiya bilan BIRGA doimiy 'tushib' turishlari (erkin tushish holatida bo'lishlari), bu 'mikrogravitatsiya' deb ataladi!"},
    {"hook": "Yorug'lik tezligi 300,000 km/s — bu qanchalik tez ekanini his qiling", "emoji": "💡",
     "caption": "Yorug'lik 1 soniyada Yer atrofini 7,5 MARTA aylanib chiqishi mumkin!\n\nQuyoshdan Yergacha bo'lgan yorug'lik esa 8 daqiqa 20 soniyada yetib keladi — demak siz Quyoshga qaraganingizda, uni 8 daqiqa OLDINGI holatida ko'rasiz!"},
    {"hook": "Suv 4°C da eng zich bo'ladi — bu ko'lning muzlashiga qanday yordam beradi?", "emoji": "❄️",
     "caption": "Odatda sovish zichlikni oshiradi, lekin suv G'ALATI: eng zich holati 4°C da, undan sovuqroqda esa yengillashadi (muz suvdan yengil)!\n\nShu sababli qish sovuqda ko'l USTKI qatlami muzlaydi, ostki qatlam esa 4°C atrofida qolib, baliqlarga yashash imkonini beradi!"},
    {"hook": "Bosim 2 atmosfera, yuza 0,5 m² bo'lsa, kuchni top", "emoji": "📏",
     "caption": "MASALA: P=2 atm (≈202,600 Pa), S=0,5m². Kuchni top.\n\nYECHIM: P=F/S → F=P×S\nF=202600×0,5=101300\n\nJavob: ≈101,3 kN"},
    {"hook": "Nega samolyot qanoti uchishga yordam beradi — Bernulli qonuni bilan tushuntirish", "emoji": "✈️",
     "caption": "Qanot shakli havoni USTKI qismdan TEZROQ, ostki qismdan SEKINROQ oqishga majburlaydi.\n\nBernulli qonuniga ko'ra, tezroq oqim — PASTROQ bosim yaratadi. Natijada qanot ostida yuqori, ustida past bosim hosil bo'ladi — bu farq samolyotni KO'TARUVCHI kuch (lift) yaratadi!"},
    {"hook": "Nega qishda metall buyum yog'ochdan sovuqroq his qilinadi, garchi harorat bir xil bo'lsa ham", "emoji": "🥶",
     "caption": "Bu — issiqlik o'tkazuvchanlik farqi! Metall issiqlikni tanangizdan JUDA TEZ oladi (yaxshi issiqlik o'tkazgich), yog'och esa sekin (yomon o'tkazgich).\n\nShuning uchun ikkisi bir xil haroratda bo'lsa ham, metall qo'lingizni tezroq soviydi — bu HARORAT emas, issiqlik OQIMI tezligi farqi!"},
    {"hook": "1kg suvni 1°C ga isitish uchun qancha energiya kerak?", "emoji": "🔥",
     "caption": "MASALA: m=1kg, ΔT=1°C. Kerakli issiqlik miqdorini top (suv solishtirma issiqlik sig'imi c=4200 J/kg°C).\n\nYECHIM: Q=cmΔT\nQ=4200×1×1=4200\n\nJavob: 4200 Joul (bu — 1 kaloriyaning taxminan 1000 barobari!)"},
    {"hook": "Nega momaqaldiroqda avval yashinni ko'ramiz, keyingina tovushini eshitamiz?", "emoji": "⛈️",
     "caption": "Yorug'lik tezligi (300,000 km/s) tovush tezligidan (340 m/s) DEYARLI CHEKSIZ marta tezroq!\n\nShuning uchun chaqmoqni deyarli DARHOL ko'ramiz, gumburlashni esa bir necha soniyadan keyin eshitamiz. Har 3 soniyalik farq ≈1 km masofani bildiradi — shu orqali chaqmoq qanchalik uzoqda ekanini hisoblash mumkin!"},
    {"hook": "Nega parashyutchi tushayotganda ma'lum tezlikdan tezroq tushmaydi?", "emoji": "🪂",
     "caption": "Bu — 'terminal tezlik' (chegara tezlik) hodisasi. Tushayotganda havo qarshiligi tezlik oshgani sari KUCHAYADI.\n\nQachonki havo qarshiligi tortishish kuchiga TENGLASHSA, tezlanish TO'XTAYDI va jism DOIMIY tezlikda tushishda davom etadi — parashyutsiz odam uchun bu ~200 km/soat atrofida!"},
    {"hook": "Elektr toki 2A, kuchlanish 12V bo'lsa, quvvatni top", "emoji": "🔋",
     "caption": "MASALA: I=2A, U=12V. Quvvatni top.\n\nYECHIM: P=UI\nP=12×2=24\n\nJavob: 24 Vatt"},
    {"hook": "Nega Oy Yerga har doim bir tomoni bilan qaraydi?", "emoji": "🌕",
     "caption": "Bu — 'tidal lock' (to'lqin qulflanishi) hodisasi. Yerning tortishish kuchi millionlab yillar davomida Oyning aylanish tezligini SEKINLASHTIRIB, uni o'z o'qi atrofida aylanishi bilan Yer atrofida aylanishini BIR XIL vaqtga (~27,3 kun) moslashtirib qo'ygan.\n\nShuning uchun biz doim Oyning FAQAT bir tomonini ko'ramiz!"},
    {"hook": "Nega issiq havo yengil, sovuq havo esa og'ir bo'ladi?", "emoji": "🎈",
     "caption": "Isitilganda molekulalar TEZROQ harakatlanadi va bir-biridan UZOQLASHADI — bu havoning zichligini KAMAYTIRADI.\n\nKamroq zich havo — yengilroq, shuning uchun issiq havo YUQORIGA ko'tariladi (issiq havo shari, isitish tizimlarining ishlashi shu tamoyilga asoslangan)!"},
    {"hook": "Tovush tezligi havoda 340 m/s, suvda esa 1480 m/s — nega suvda tezroq?", "emoji": "🌊",
     "caption": "Tovush — molekulalar orasidagi TITRASH orqali tarqaladi. Suv molekulalari havodagidan ko'ra bir-biriga YAQINROQ joylashgan.\n\nShuning uchun titrash tezroq 'uzatiladi' — suvda tovush havodagidan qariyb 4,3 marta tezroq tarqaladi!"},
    {"hook": "Nega uchqun (statik elektr) quruq qishda ko'proq his qilinadi?", "emoji": "⚡",
     "caption": "Havo namligi past bo'lganda (qishda isitilgan xonalarda), zaryadlar teringizda TO'PLANIB qolishga moyil bo'ladi (namlik zaryadni tezroq 'tarqatib' yuborardi).\n\nMetall buyumga tegganingizda to'plangan zaryad birdaniga OQIB o'tadi — buni uchqun va yengil elektr zarbasi sifatida his qilamiz!"},
    {"hook": "Nega kosmosda kiyilgan skafandr og'ir bo'lsa ham, kosmonavt uni ko'tarolmaydi deb o'ylamaymiz?", "emoji": "🌌",
     "caption": "Vazn (og'irlik) — tortishish kuchi tufayli paydo bo'ladi (F=mg). Kosmosda mikrogravitatsiya sharoitida vazn DEYARLI YO'Q, lekin MASSA (moddaning miqdori) o'zgarmaydi!\n\nShuning uchun skafandr 'og'ir' emas (vaznsiz), lekin uni tezlashtirish/to'xtatish uchun hali ham katta KUCH kerak — bu massaning inertsiya xossasi!"},
]

CHANNELS = {
    "math_olimjon": MATH_OLIMJON,
    "faktura": FAKTURA,
    "matematika_milliy": MATEMATIKA_MILLIY,
    "fizika_milliy": FIZIKA_MILLIY,
}
